# Use root/example as user/password credentials
version: '3.2'

services:
  web:
    build: .
    restart: always
    ports:
      - 9999:80
    links:
      - mysql:mysql
    volumes:
      - "${HOME}/Docker/Production/TPTracker-golden-image/uploads:/var/www/html/TPTracker/uploads"
      - "${HOME}/Docker/Production/TPTracker-golden-image/images:/var/www/html/TPTracker/images/TSruns"

  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "*23Ft198"
    volumes:
      - /home/michael/Docker/Production/TPTracker-golden-image/mysql:/var/lib/mysql

